version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: kms-postgres
    environment:
      POSTGRES_DB: knowledge_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kms-network

  redis:
    image: redis:7-alpine
    container_name: kms-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - kms-network

volumes:
  postgres_data:
  redis_data:

networks:
  kms-network:
    driver: bridge